// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class FingerprintNativeConfig {
  FingerprintNativeConfig({
    required this.apiKey,
    this.region,
    this.endpoint,
    this.endpointFallbacks,
    required this.pluginVersion,
    required this.allowUseOfLocationData,
    this.locationTimeoutMillis,
  });

  String apiKey;

  String? region;

  String? endpoint;

  List<String>? endpointFallbacks;

  String pluginVersion;

  bool allowUseOfLocationData;

  int? locationTimeoutMillis;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      region,
      endpoint,
      endpointFallbacks,
      pluginVersion,
      allowUseOfLocationData,
      locationTimeoutMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static FingerprintNativeConfig decode(Object result) {
    result as List<Object?>;
    return FingerprintNativeConfig(
      apiKey: result[0]! as String,
      region: result[1] as String?,
      endpoint: result[2] as String?,
      endpointFallbacks: (result[3] as List<Object?>?)?.cast<String>(),
      pluginVersion: result[4]! as String,
      allowUseOfLocationData: result[5]! as bool,
      locationTimeoutMillis: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FingerprintNativeConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) && _deepEquals(region, other.region) && _deepEquals(endpoint, other.endpoint) && _deepEquals(endpointFallbacks, other.endpointFallbacks) && _deepEquals(pluginVersion, other.pluginVersion) && _deepEquals(allowUseOfLocationData, other.allowUseOfLocationData) && _deepEquals(locationTimeoutMillis, other.locationTimeoutMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FingerprintNativeConfig(apiKey: $apiKey, region: $region, endpoint: $endpoint, endpointFallbacks: $endpointFallbacks, pluginVersion: $pluginVersion, allowUseOfLocationData: $allowUseOfLocationData, locationTimeoutMillis: $locationTimeoutMillis)';
  }
}

class FingerprintNativeResult {
  FingerprintNativeResult({
    required this.eventId,
    required this.visitorId,
    this.suspectScore,
    this.sealedResult,
  });

  String eventId;

  String visitorId;

  int? suspectScore;

  String? sealedResult;

  List<Object?> _toList() {
    return <Object?>[
      eventId,
      visitorId,
      suspectScore,
      sealedResult,
    ];
  }

  Object encode() {
    return _toList();  }

  static FingerprintNativeResult decode(Object result) {
    result as List<Object?>;
    return FingerprintNativeResult(
      eventId: result[0]! as String,
      visitorId: result[1]! as String,
      suspectScore: result[2] as int?,
      sealedResult: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FingerprintNativeResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(eventId, other.eventId) && _deepEquals(visitorId, other.visitorId) && _deepEquals(suspectScore, other.suspectScore) && _deepEquals(sealedResult, other.sealedResult);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FingerprintNativeResult(eventId: $eventId, visitorId: $visitorId, suspectScore: $suspectScore, sealedResult: $sealedResult)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is FingerprintNativeConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is FingerprintNativeResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return FingerprintNativeConfig.decode(readValue(buffer)!);
      case 130:
        return FingerprintNativeResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FingerprintHostApi {
  /// Constructor for [FingerprintHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FingerprintHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Builds the native Fingerprint client immediately so location can warm
  /// before identification. get still carries config and reuses this client.
  /// https://docs.fingerprint.com/docs/ios-sdk
  Future<void> create(FingerprintNativeConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fpjs_pro_plugin.FingerprintHostApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<FingerprintNativeResult> get(FingerprintNativeConfig config, Map<String?, Object?>? tags, String? linkedId, int? timeoutMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fpjs_pro_plugin.FingerprintHostApi.get$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config, tags, linkedId, timeoutMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as FingerprintNativeResult;
  }
}
