plugins {
    id 'com.android.library'
}

apply from: 'fingerprint.gradle'

group 'com.fingerprint.flutter'
version '4.13.1'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.fpregistry.io/releases' }
        maven { url 'https://jitpack.io' }
    }
}

android {
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion 24
    }

    if (project.android.hasProperty("namespace")) {
        namespace 'com.fingerprint.flutter'
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
    }
}

dependencies {
    implementation "com.fingerprint.android:sdk:$fingerprint_native_sdk_version"
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.jetbrains.kotlin:kotlin-test"
    testImplementation "org.mockito:mockito-core:5.14.2"
}
