plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

apply from: 'fingerprint.gradle'

group 'com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin'
version '4.13.1'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.fpregistry.io/releases' }
        maven { url 'https://jitpack.io' }
    }
}

android {
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 24
    }

    if (project.android.hasProperty("namespace")) {
        namespace 'com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin'
    }
}

dependencies {
    implementation "com.fingerprint.android:sdk:$fingerprint_native_sdk_version"
}
