import 'dart:async';

import 'package:fpjs_pro_plugin/fingerprint_platform_interface.dart';
import 'package:fpjs_pro_plugin/method_channel_fingerprint.dart';
import 'package:fpjs_pro_plugin/region.dart';
import 'package:fpjs_pro_plugin/result.dart';

// Update it on each release
const pluginVersion = '4.13.1';

/// A plugin that accesses native FingerprintJS Pro libraries to get a device identifier
class FpjsProPlugin {
  /// The channel the native implementation listens on
  static const channelName = MethodChannelFingerprint.channelName;

  static var _isInitialized = false;

  static FingerprintPlatform get _platform => FingerprintPlatform.instance;

  /// Initializes the FingerprintJS Pro client
  /// Throws a [PlatformException] if [apiKey] is missing
  static Future<void> initFpjs(String apiKey,
      {String? endpoint,
      List<String>? endpointFallbacks,
      String? scriptUrlPattern,
      List<String>? scriptUrlPatternFallbacks,
      Region? region,
      bool? allowUseOfLocationData,
      int? locationTimeoutMillisAndroid,
      bool extendedResponseFormat = false}) async {
    await _platform.init(FingerprintConfig(
      apiKey: apiKey,
      endpoint: endpoint,
      endpointFallbacks: endpointFallbacks,
      scriptUrlPattern: scriptUrlPattern,
      scriptUrlPatternFallbacks: scriptUrlPatternFallbacks,
      region: region,
      allowUseOfLocationData: allowUseOfLocationData,
      locationTimeoutMillisAndroid: locationTimeoutMillisAndroid,
      extendedResponseFormat: extendedResponseFormat,
    ));
    _isInitialized = true;
  }

  /// Returns the visitorId generated by the Fingerprint Pro client
  /// Support [tags](https://docs.fingerprint.com/reference/get-function#tag)
  /// Support [linkedId](https://docs.fingerprint.com/reference/get-function#linkedid)
  /// Support [timeoutMs](https://docs.fingerprint.com/reference/get-function#timeout)
  /// Throws a [FingerprintProError] if identification request fails for any reason
  static Future<String?> getVisitorId(
      {Map<String, dynamic>? tags, String? linkedId, int? timeoutMs}) async {
    _checkInitialized();
    return _platform.getVisitorId(
        tags: tags, linkedId: linkedId, timeoutMs: timeoutMs);
  }

  /// Returns the visitor data generated by the Fingerprint Pro client
  /// Support [tags](https://docs.fingerprint.com/reference/get-function#tag)
  /// Support [linkedId](https://docs.fingerprint.com/reference/get-function#linkedid)
  /// Support [timeoutMs](https://docs.fingerprint.com/reference/get-function#timeout)
  /// Throws a [FingerprintProError] if identification request fails for any reason
  static Future<T> getVisitorData<T extends FingerprintJSProResponse>(
      {Map<String, dynamic>? tags, String? linkedId, int? timeoutMs}) async {
    _checkInitialized();
    final visitorData = await _platform.getVisitorData(
        tags: tags, linkedId: linkedId, timeoutMs: timeoutMs);
    return visitorData as T;
  }

  static void _checkInitialized() {
    if (!_isInitialized) {
      throw Exception(
          'You need to initialize the FPJS Client first by calling the "initFpjs" method');
    }
  }
}
