// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FingerprintApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class FingerprintNativeConfig (
  val apiKey: String,
  val region: String? = null,
  val endpoints: List<String>? = null,
  val pluginVersion: String,
  val allowUseOfLocationData: Boolean,
  val locationTimeoutMillis: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FingerprintNativeConfig {
      val apiKey = pigeonVar_list[0] as String
      val region = pigeonVar_list[1] as String?
      val endpoints = pigeonVar_list[2] as List<String>?
      val pluginVersion = pigeonVar_list[3] as String
      val allowUseOfLocationData = pigeonVar_list[4] as Boolean
      val locationTimeoutMillis = pigeonVar_list[5] as Long?
      return FingerprintNativeConfig(apiKey, region, endpoints, pluginVersion, allowUseOfLocationData, locationTimeoutMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      region,
      endpoints,
      pluginVersion,
      allowUseOfLocationData,
      locationTimeoutMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FingerprintNativeConfig
    return FingerprintApiPigeonUtils.deepEquals(this.apiKey, other.apiKey) && FingerprintApiPigeonUtils.deepEquals(this.region, other.region) && FingerprintApiPigeonUtils.deepEquals(this.endpoints, other.endpoints) && FingerprintApiPigeonUtils.deepEquals(this.pluginVersion, other.pluginVersion) && FingerprintApiPigeonUtils.deepEquals(this.allowUseOfLocationData, other.allowUseOfLocationData) && FingerprintApiPigeonUtils.deepEquals(this.locationTimeoutMillis, other.locationTimeoutMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.region)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.endpoints)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.pluginVersion)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.allowUseOfLocationData)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.locationTimeoutMillis)
    return result
  }
  override fun toString(): String {
    return "FingerprintNativeConfig(apiKey=$apiKey, region=$region, endpoints=$endpoints, pluginVersion=$pluginVersion, allowUseOfLocationData=$allowUseOfLocationData, locationTimeoutMillis=$locationTimeoutMillis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FingerprintNativeResult (
  val eventId: String,
  val visitorId: String,
  val suspectScore: Long? = null,
  val sealedResult: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FingerprintNativeResult {
      val eventId = pigeonVar_list[0] as String
      val visitorId = pigeonVar_list[1] as String
      val suspectScore = pigeonVar_list[2] as Long?
      val sealedResult = pigeonVar_list[3] as String?
      return FingerprintNativeResult(eventId, visitorId, suspectScore, sealedResult)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventId,
      visitorId,
      suspectScore,
      sealedResult,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FingerprintNativeResult
    return FingerprintApiPigeonUtils.deepEquals(this.eventId, other.eventId) && FingerprintApiPigeonUtils.deepEquals(this.visitorId, other.visitorId) && FingerprintApiPigeonUtils.deepEquals(this.suspectScore, other.suspectScore) && FingerprintApiPigeonUtils.deepEquals(this.sealedResult, other.sealedResult)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.eventId)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.visitorId)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.suspectScore)
    result = 31 * result + FingerprintApiPigeonUtils.deepHash(this.sealedResult)
    return result
  }
  override fun toString(): String {
    return "FingerprintNativeResult(eventId=$eventId, visitorId=$visitorId, suspectScore=$suspectScore, sealedResult=$sealedResult)"
  }
}
private open class FingerprintApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FingerprintNativeConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FingerprintNativeResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FingerprintNativeConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is FingerprintNativeResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FingerprintHostApi {
  fun get(config: FingerprintNativeConfig, tags: Map<Any?, Any?>?, linkedId: String?, timeoutMs: Long?, callback: (Result<FingerprintNativeResult>) -> Unit)

  companion object {
    /** The codec used by FingerprintHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FingerprintApiPigeonCodec()
    }
    /** Sets up an instance of `FingerprintHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FingerprintHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fpjs_pro_plugin.FingerprintHostApi.get$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as FingerprintNativeConfig
            val tagsArg = args[1] as Map<Any?, Any?>?
            val linkedIdArg = args[2] as String?
            val timeoutMsArg = args[3] as Long?
            api.get(configArg, tagsArg, linkedIdArg, timeoutMsArg) { result: Result<FingerprintNativeResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FingerprintApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FingerprintApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
