// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum FingerprintApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct FingerprintNativeConfig: Hashable, CustomStringConvertible {
  var apiKey: String
  var region: String? = nil
  var endpoint: String? = nil
  var endpointFallbacks: [String]? = nil
  var pluginVersion: String
  var allowUseOfLocationData: Bool
  var locationTimeoutMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FingerprintNativeConfig? {
    let apiKey = pigeonVar_list[0] as! String
    let region: String? = nilOrValue(pigeonVar_list[1])
    let endpoint: String? = nilOrValue(pigeonVar_list[2])
    let endpointFallbacks: [String]? = nilOrValue(pigeonVar_list[3])
    let pluginVersion = pigeonVar_list[4] as! String
    let allowUseOfLocationData = pigeonVar_list[5] as! Bool
    let locationTimeoutMillis: Int64? = nilOrValue(pigeonVar_list[6])

    return FingerprintNativeConfig(
      apiKey: apiKey,
      region: region,
      endpoint: endpoint,
      endpointFallbacks: endpointFallbacks,
      pluginVersion: pluginVersion,
      allowUseOfLocationData: allowUseOfLocationData,
      locationTimeoutMillis: locationTimeoutMillis
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      region,
      endpoint,
      endpointFallbacks,
      pluginVersion,
      allowUseOfLocationData,
      locationTimeoutMillis,
    ]
  }
  static func == (lhs: FingerprintNativeConfig, rhs: FingerprintNativeConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FingerprintApiPigeonInternal.deepEquals(lhs.apiKey, rhs.apiKey) && FingerprintApiPigeonInternal.deepEquals(lhs.region, rhs.region) && FingerprintApiPigeonInternal.deepEquals(lhs.endpoint, rhs.endpoint) && FingerprintApiPigeonInternal.deepEquals(lhs.endpointFallbacks, rhs.endpointFallbacks) && FingerprintApiPigeonInternal.deepEquals(lhs.pluginVersion, rhs.pluginVersion) && FingerprintApiPigeonInternal.deepEquals(lhs.allowUseOfLocationData, rhs.allowUseOfLocationData) && FingerprintApiPigeonInternal.deepEquals(lhs.locationTimeoutMillis, rhs.locationTimeoutMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FingerprintNativeConfig")
    FingerprintApiPigeonInternal.deepHash(value: apiKey, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: region, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: endpoint, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: endpointFallbacks, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: pluginVersion, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: allowUseOfLocationData, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: locationTimeoutMillis, hasher: &hasher)
  }

  public var description: String {
    return "FingerprintNativeConfig(apiKey: \(String(describing: apiKey)), region: \(String(describing: region)), endpoint: \(String(describing: endpoint)), endpointFallbacks: \(String(describing: endpointFallbacks)), pluginVersion: \(String(describing: pluginVersion)), allowUseOfLocationData: \(String(describing: allowUseOfLocationData)), locationTimeoutMillis: \(String(describing: locationTimeoutMillis)))"
  }
}

/// Pigeon copy of the Android/iOS SDK identification response.
///
/// `visitorId` is `String` because those SDKs always send a string. Empty means
/// hidden. Dart `FingerprintResult` turns empty into null.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FingerprintNativeResult: Hashable, CustomStringConvertible {
  var eventId: String
  var visitorId: String
  var suspectScore: Int64? = nil
  var sealedResult: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FingerprintNativeResult? {
    let eventId = pigeonVar_list[0] as! String
    let visitorId = pigeonVar_list[1] as! String
    let suspectScore: Int64? = nilOrValue(pigeonVar_list[2])
    let sealedResult: String? = nilOrValue(pigeonVar_list[3])

    return FingerprintNativeResult(
      eventId: eventId,
      visitorId: visitorId,
      suspectScore: suspectScore,
      sealedResult: sealedResult
    )
  }
  func toList() -> [Any?] {
    return [
      eventId,
      visitorId,
      suspectScore,
      sealedResult,
    ]
  }
  static func == (lhs: FingerprintNativeResult, rhs: FingerprintNativeResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FingerprintApiPigeonInternal.deepEquals(lhs.eventId, rhs.eventId) && FingerprintApiPigeonInternal.deepEquals(lhs.visitorId, rhs.visitorId) && FingerprintApiPigeonInternal.deepEquals(lhs.suspectScore, rhs.suspectScore) && FingerprintApiPigeonInternal.deepEquals(lhs.sealedResult, rhs.sealedResult)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FingerprintNativeResult")
    FingerprintApiPigeonInternal.deepHash(value: eventId, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: visitorId, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: suspectScore, hasher: &hasher)
    FingerprintApiPigeonInternal.deepHash(value: sealedResult, hasher: &hasher)
  }

  public var description: String {
    return "FingerprintNativeResult(eventId: \(String(describing: eventId)), visitorId: \(String(describing: visitorId)), suspectScore: \(String(describing: suspectScore)), sealedResult: \(String(describing: sealedResult)))"
  }
}

private class FingerprintApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return FingerprintNativeConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return FingerprintNativeResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FingerprintApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FingerprintNativeConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? FingerprintNativeResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FingerprintApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FingerprintApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FingerprintApiPigeonCodecWriter(data: data)
  }
}

class FingerprintApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FingerprintApiPigeonCodec(readerWriter: FingerprintApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FingerprintHostApi {
  /// Builds the native Fingerprint client immediately so location can warm
  /// before identification. get still carries config and reuses this client,
  /// so two Dart clients stay independent if create was skipped.
  /// https://docs.fingerprint.com/docs/ios-sdk
  func create(config: FingerprintNativeConfig) throws
  func get(config: FingerprintNativeConfig, tags: [String?: Any?]?, linkedId: String?, timeoutMs: Int64?, completion: @escaping (Result<FingerprintNativeResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FingerprintHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FingerprintApiPigeonCodec.shared }
  /// Sets up an instance of `FingerprintHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FingerprintHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Builds the native Fingerprint client immediately so location can warm
    /// before identification. get still carries config and reuses this client,
    /// so two Dart clients stay independent if create was skipped.
    /// https://docs.fingerprint.com/docs/ios-sdk
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fingerprint_flutter.FingerprintHostApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! FingerprintNativeConfig
        do {
          try api.create(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let getChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fingerprint_flutter.FingerprintHostApi.get\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! FingerprintNativeConfig
        let tagsArg: [String?: Any?]? = nilOrValue(args[1])
        let linkedIdArg: String? = nilOrValue(args[2])
        let timeoutMsArg: Int64? = nilOrValue(args[3])
        api.get(config: configArg, tags: tagsArg, linkedId: linkedIdArg, timeoutMs: timeoutMsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getChannel.setMessageHandler(nil)
    }
  }
}
