name: 'Build and run checks'
on:
  workflow_call:

jobs:
  build-and-run-checks:
    name: 'Build and run checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and set Flutter version
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 #v2.23.0
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
      - name: Create .env.local
        run: cp ./example/.env ./example/.env.local
        shell: bash
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
