name: 'Build and run checks'
on:
  workflow_call:

jobs:
  build-and-run-checks:
    name: "Build and run checks (Flutter ${{ matrix['flutter-version'] || 'latest stable' }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flutter-version: ['3.32.0', '']
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install and set Flutter version
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 #v2.23.0
        with:
          channel: 'stable'
          flutter-version: ${{ matrix.flutter-version }}
      - name: Restore packages
        run: flutter pub get
      - name: Create .env.local
        run: cp ./example/.env ./example/.env.local
        shell: bash
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
