name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: 'production'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # This action adds a token needed for pub.dev
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install and set Flutter version
        uses: subosito/flutter-action@0c3f14223a08fa950c8a4c00bcfb834e65744135
        with:
          channel: 'stable'
      - name: Publish to pub.dev
        run: flutter pub publish --force
