name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: 'production'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # This action adds a token needed for pub.dev
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install and set Flutter version
        uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
        with:
          channel: 'stable'
      - name: Publish to pub.dev
        run: flutter pub publish --force --verbose
