name: Release
on:
  push:
    branches:
      - main
      - test
jobs:
  test:
    name: 'Build and check code before release'
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    uses: ./.github/workflows/build-and-run-check-workflow.yml

  release:
    name: 'Release using changesets'
    needs: test
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      appId: ${{ vars.APP_ID }}
      runnerAppId: ${{ vars.RUNNER_APP_ID }}
      version-command: pnpm changeset:version
      publish-command: pnpm changeset:publish
      language: flutter
      language-version: '3.x'
      prepare-command: |
        sudo gem install -n /usr/local/bin cocoapods
        pod --version
        echo "flutter.sdk=$FLUTTER_ROOT" > $GITHUB_WORKSPACE/android/local.properties
      # Required by Gradle
      java-version: '17'
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      RUNNER_APP_PRIVATE_KEY: ${{ secrets.RUNNER_APP_PRIVATE_KEY }}
