name: Release
on:
  push:
    branches:
      - main
      - test
jobs:
  test:
    name: 'Build and check code before release'
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    uses: ./.github/workflows/build-and-run-check-workflow.yml

  release:
    name: 'Prepare new version'
    needs: test
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-server-sdk.yml@v1
    with:
      language: flutter
      language-version: '3.x'
      appId: ${{ vars.APP_ID }}
      semantic-release-extra-plugins: '@fingerprintjs/semantic-release-native-dependency-plugin@^1.1.0'
      prepare-command: 'echo "flutter.sdk=$FLUTTER_ROOT" > $GITHUB_WORKSPACE/android/local.properties'
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
